---
name: 'sarif-to-markdown'
description: 'Converts SARIF reports to Markdown'
inputs:
  input:
    description: |
      Location of the SARIF report
    required: true
    default: 'security.sarif'
  output:
    description: |
      Location of the markdown report
    required: true
    default: 'security_report.md'

runs:
  using: "node16"
  main: "src/action.js"
